apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ml-ambulance-ufe-content
spec:
  microFrontend: ml-ambulance-ufe
  element: ml-ambulance-wl-app
  attributes:
    - name: base-path
      value: /ml-ambulance-wl/  
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?ml-ambulance-wl(/.*)?$"